trigger:
- main
#pool:
#  vmImage: 'ubuntu-latest'
#steps:
#- task: terraformInstaller@0
#  inputs:
#    terraformVersion: '0.14.5'
#  displayName: Install Terraform
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: terraformInstaller@0
  inputs:
    terraformVersion: '0.14.5'
  displayName: Install Terraform

- task: terraform@0
  inputs:
    command: 'init'
    #providerAzureConnectedServiceName: 'MTC Denver Sandbox'
    #backendAzureProviderStorageAccountName: 'mtcdenterraformsandbox'
  displayName: Terraform Init
    
- task: terraform@0
  inputs:
    command: 'plan'
    #providerAzureConnectedServiceName: 'MTC Denver Sandbox'
    args:  -out=tfplan.out
  displayName: Terraform Plan