trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: terraformInstaller@0
  inputs:
    terraformVersion: '0.14.5'
  displayName:  ms-devlabs.custom-terraform-tasks


#- task: AWSShellScript@1
  #inputs:
    #awsCredentials: 'AWS-SANDBOX'
    #regionName: 'us-east-1'
    #scriptType: 'inline'
    #inlineScript: 'cdk deploy --ci --require-approval never'
    #disableAutoCwd: true
    #workingDirectory: '$(System.DefaultWorkingDirectory)'
    #failOnStandardError: false
 # displayName: 'cdk deploy'

#- task: terraform@0
  #inputs:
  #  command: 'init'
    #providerAzureConnectedServiceName: 'MTC Denver Sandbox'
    #backendAzureProviderStorageAccountName: 'mtcdenterraformsandbox'
 # displayName: Terraform Init
    
#- task: terraform@0
  #inputs:
    #command: 'plan'
    #providerAzureConnectedServiceName: 'MTC Denver Sandbox'
   # args:  -out=tfplan.out
  #displayName: Terraform Plan


  #the task name terraformInstaller is ambiguous. Specify one of the following identifiers to resolve the ambiguity: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller, charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller