trigger:
- main
#pool:
#  vmImage: 'ubuntu-latest'
#steps:
#- task: terraformInstaller@0
#  inputs:
#    terraformVersion: '0.14.5'
#  displayName: Install Terraform

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: terraformInstaller@0
  inputs:
    terraformVersion: '0.12.12'
  displayName: Install Terraform