trigger:
- main
#pool:
#  vmImage: 'ubuntu-latest'
#steps:
#- task: terraformInstaller@0
#  inputs:
#    terraformVersion: '0.14.5'
#  displayName: Install Terraform

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: terraformInstaller@0
  inputs:
    terraformVersion: '0.14.5'
  displayName: Install Terraform
