# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

- script: |
    terraform init
    cd https://dev.azure.com/samargooda368/demo-terraform/_build/results?buildId=5&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=13
    terraform plan
  displayName: 'Run a multi-line script'
